package com.example.viewmodel

import android.app.Application
import android.content.Intent
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await

class AuthViewModel(application: Application) : AndroidViewModel(application) {
    private val auth: FirebaseAuth = FirebaseAuth.getInstance()
    private val googleSignInClient: GoogleSignInClient

    private val _user = MutableStateFlow<FirebaseUser?>(auth.currentUser)
    val user: StateFlow<FirebaseUser?> = _user

    private val _isLoading = MutableStateFlow(false)
    val isLoading: StateFlow<Boolean> = _isLoading
    
    private val _error = MutableStateFlow<String?>(null)
    val error: StateFlow<String?> = _error

    init {
        val context = application.applicationContext
        // Use R.string directly to ensure we get the client ID generated by google-services
        val clientId = try { context.getString(com.example.R.string.default_web_client_id) } catch (e: Exception) { "" }

        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(clientId)
            .requestEmail()
            .build()
        googleSignInClient = GoogleSignIn.getClient(context, gso)
    }

    fun getGoogleSignInIntent(): Intent {
        return googleSignInClient.signInIntent
    }

    fun updateUsername(newName: String) {
        viewModelScope.launch {
            _isLoading.value = true
            try {
                val user = auth.currentUser ?: return@launch
                val profileUpdates = com.google.firebase.auth.UserProfileChangeRequest.Builder()
                    .setDisplayName(newName)
                    .build()
                user.updateProfile(profileUpdates).await()
                
                // Also update in Firestore if using it
                val db = com.google.firebase.firestore.FirebaseFirestore.getInstance()
                db.collection("users").document(user.uid).update("displayName", newName).await()
                
                // Reload user to update flow
                auth.currentUser?.reload()?.await()
                _user.value = auth.currentUser
                _error.value = null
            } catch (e: Exception) {
                _error.value = e.localizedMessage
            } finally {
                _isLoading.value = false
            }
        }
    }

    fun handleGoogleSignInResult(intent: Intent?) {
        _isLoading.value = true
        viewModelScope.launch {
            try {
                val task = GoogleSignIn.getSignedInAccountFromIntent(intent)
                val account = task.await()
                val credential = GoogleAuthProvider.getCredential(account.idToken, null)
                val authResult = auth.signInWithCredential(credential).await()
                _user.value = authResult.user
            } catch (e: Exception) {
                // Return generic message if needed
                _error.value = e.localizedMessage ?: "Google Sign-In failed"
            } finally {
                _isLoading.value = false
            }
        }
    }

    fun signInWithEmail(email: String, pass: String) {
        _isLoading.value = true
        viewModelScope.launch {
            try {
                val result = auth.signInWithEmailAndPassword(email, pass).await()
                _user.value = result.user
            } catch (e: Exception) {
                // If sign in fails, maybe they need to register? We only do simple.
                try {
                    val result = auth.createUserWithEmailAndPassword(email, pass).await()
                    _user.value = result.user
                } catch(e2: Exception) {
                    _error.value = e2.localizedMessage ?: "Email Auth failed"
                }
            } finally {
                _isLoading.value = false
            }
        }
    }

    fun signInAsGuest() {
        _isLoading.value = true
        viewModelScope.launch {
            try {
                val result = auth.signInAnonymously().await()
                _user.value = result.user
            } catch(e: Exception) {
                _error.value = e.localizedMessage ?: "Guest Auth failed"
            } finally {
                _isLoading.value = false
            }
        }
    }

    fun clearError() {
        _error.value = null
    }

    fun signOut() {
        auth.signOut()
        googleSignInClient.signOut()
        _user.value = null
    }
}
